NG-4471 Release judo generator commons
BlackBeltTechnology/judo-generator-commons pull request #19
Opened 2023-02-21 13:37 UTC by gaborflorian

2023-02-22 17:13 UTC, bencegelei approved these changes

2023-02-22 19:10 UTC, robertcsakany requested changes

2023-02-22 19:10 UTC, robertcsakany commented on .github/workflows/release.yml
>          run: |-
Is the reference matching with the output name?

2023-02-22 19:10 UTC, robertcsakany commented on .github/workflows/create-release-tagged.yml
> -          echo "::set-output name=branch::$branch"
User lowercase characters:

 echo "version=$version" >> $GITHUB_OUTPUT
 echo "branch=$branch" >> $GITHUB_OUTPUT

2023-02-23 10:36 UTC, gaborflorian commented on .github/workflows/create-release-tagged.yml
> -          echo "::set-output name=branch::$branch"
[fd3af97](https://github.com/BlackBeltTechnology/judo-generator-commons/pull/19/commits/fd3af97cbc5d247c8325d245b1dd3b67306bf939)

2023-02-23 10:37 UTC, gaborflorian commented on .github/workflows/release.yml
>          run: |-
[fd3af97](https://github.com/BlackBeltTechnology/judo-generator-commons/pull/19/commits/fd3af97cbc5d247c8325d245b1dd3b67306bf939)

2023-02-23 10:56 UTC, gaborflorian commented on .github/workflows/release.yml
>          run: |-
Yes it is matching.

for example:
in  Calculate version number
echo "VERSION=${VERSION_NUMBER}" >> $GITHUB_OUTPUT 
used in
Create version tag 
steps.version.outputs.version is the calculated version and the created version tag has correct version.

But for the consistency, I renamed the set-output variable names with lowercase characters.

2023-02-23 14:39 UTC, robertcsakany approved these changes

2023-02-24 08:33 UTC, fmagnucz approved these changes

2023-02-28 15:03 UTC, merged